# Generated by Django 6.0.5 on 2026-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_attachments_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachments",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="attachments/", verbose_name="Фото"
            ),
        ),
    ]
