# Generated by Django 6.0.5 on 2026-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0006_alter_attachments_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("item", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
